language: objective-c
osx_image: xcode7.1

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - IOS_FRAMEWORK_SCHEME="Shoyu"
    - IOS_SDK=iphonesimulator9.1
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 6"       SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK" 
    - DESTINATION="OS=9.1,name=iPhone 6 Plus"   SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"    

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project Shoyu.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
